server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://120.79.251.229:3306/wgj?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: Dell@123
    username: root
    password: hlx520you1314


  thymeleaf:
    cache: false
    check-template: false

  redis:
    host: 47.92.127.186
    port: 6379
    database: 0                       #默认是索引为0的数据库
    password:
    timeout:

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dpk.wgj.bean
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true             #二级缓存的全局开关

com:
  dpk:
    wgj:
      windows-path: d:/wgj/
      linux-path: /wgj
      images-path: file:d:/wgj/     #访问外部静态文件的路径

jwt:
  secret: zhoulinSecret             #签名加密
  header: token
  validity-time: 43200000           #token有效时间


